config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  get 'home/index' => '/'
  root 'home#index'
  get 'home/about' => 'home#about'
  get 'home/contact' => 'home#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about

  end
  def contact

  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<!DOCTYPE html>

<html lang="ja">

<head>
 <title> NAMAKEMONO </title>
<!-- meta -->
 <meta charaset = "utf-8">
 <meta name="viewport" content="width=device-width", "initial-scale=1">
 <meta name="description" content="This is my first portfolio and photo gallery project.">
 <meta name="keywords" content="photo, 写真, 風景, 景色, 夜景, landscape, view, nightscape, ポートレート, beginner">
 <meta name="author" content="Kzm9298">

<!--Google Tag Manager-->
  <script>
  </script>
<!--End GTM-->

<!-- stylesheet -->
<%= stylesheet_link_tag "style/about", :media => "all" %>
<!-- // stylesheet -->

<!-- links js,img etc...-->

<!--  -->
<!-- // links -->
</head>

<body class="index">
  <!-- GTM (noscript) -->
  <!-- // GTM (noscript) -->
       <header>
           <!-- class="inside" -->
          <div class="bkRGBA">
            <a href="."  ><img src="\assets\menu.png" class="menu_bottom" alt="" width="40px" height="40px"></a>
            <h1><img src="\assets\Title.png" height="86px", width="308" class="title_image" /></h1>
          </div>


      </header>

<!-- main -->
<main class="clear_box">


</main>

<footer class="clear_box">
    <p>(c) @kazenomonon</p>
</footer>
</body>
</html>

app/views/home/contact.html.erb
<!DOCTYPE html>

<html lang="ja">

<head>
 <title> NAMAKEMONO </title>
<!-- meta -->
 <meta charaset = "utf-8">
 <meta name="viewport" content="width=device-width", "initial-scale=1">
 <meta name="description" content="This is my first portfolio and photo gallery project.">
 <meta name="keywords" content="photo, 写真, 風景, 景色, 夜景, landscape, view, nightscape, ポートレート, beginner">
 <meta name="author" content="Kzm9298">

<!--Google Tag Manager-->
  <script>
  </script>
<!--End GTM-->

<!-- stylesheet -->
<%= stylesheet_link_tag "style/contact", :media => "all" %>
<!-- // stylesheet -->

<!-- links js,img etc...-->

<!--  -->
<!-- // links -->
</head>

<body class="index">
  <!-- GTM (noscript) -->
  <!-- // GTM (noscript) -->
       <header>
           <!-- class="inside" -->
          <div class="bkRGBA">
            <a href="."  ><img src="\assets\menu.png" class="menu_bottom" alt="" width="40px" height="40px"></a>
            <h1><img src="\assets\Title.png" height="86px", width="308" class="title_image" /></h1>
          </div>


      </header>

<!-- main -->
<main class="clear_box">
    <section>
       <img src="\assets\topic3.JPG" width=600 height=auto />
    </section>
    <section>
      <h1>Contact Form</h1>
      <form method="GET" class="contact_form">
       <input type="text" name="Name" placeholder="Name" required/></br>
       <input type="text" name="email" placeholder="Email" required/></br>
       <input type="text" name="title" placeholder="Title" required/></br></br>
       <textarea name="message" placeholder="Message" cols="40" rows="20" required></textarea></br>
       <input type="submit" value="Send"/>
      </form>
    </section>


</main>

<footer class="clear_box">
    <p>(c) @kazenomonon</p>
</footer>
</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
 <title> NAMAKEMONO </title>
<!-- meta -->
 <meta charaset = "utf-8">
 <meta name="viewport" content="width=device-width", "initial-scale=1">
 <meta name="description" content="This is my first portfolio and photo gallery project.">
 <meta name="keywords" content="photo, 写真, 風景, 景色, 夜景, landscape, view, nightscape, ポートレート, beginner">
 <meta name="author" content="Kzm9298">



<!--Google Tag Manager-->

<!--End GTM-->

<!-- stylesheet -->
<link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Open+Sans+Condensed:ital,wght@0,300;1,300&display=swap" rel="stylesheet">
<%= stylesheet_link_tag "style/home", :media => "all" %>
<!-- // stylesheet -->

<!-- links js,img etc...-->

<!--  -->
<!-- // links -->
</head>

<body>
  <section>
    <div class="bkRGBA">
      <div id="title_header">
        <img src="assets/Title.png" id="title_img" width=270px height=auto/>
        <ul id="menu">
          <li>
            <p style="text-decoration:none;">
              <%= link_to "About", home_about_path %>
            </p>
          </li>
          <li>
            <a href="#link" style="text-decoration:none;">
              Photos
            </a>
          </li>
          <li>
             <p style="text-decoration:none;">
                <%= link_to "Contact", home_contact_path %>
             </p>
          </li>
        </ul>
      </div>
    </div>

    <div id="head_image">
      <img src="assets/DSC_0974.jpg" id="head_shot" width=1216px height=auto/>
      <!-- <img src="img/IMG_20190514_170659_991_aaa.jpg" id="head_shot" width=1216px height=auto /> -->
    </div>
  </section>

  <section id="content_images">
    <a name="link"></a>
    <div id="Photos">
      <img src="assets\DSC_0914-Edit.JPG"   />
      <img src="assets\IMG_20200501_225401.jpg"   />
      <img src="assets\IMG_20191104_183514_297.jpg"   />
      <img src="assets\IMG_20190514_170659_991_aaa.jpg"   />
      <img src="assets\IMG_20191105_083555_778.jpg"   />
      <img src="assets\DSC_0755-Edit.JPG"   />
      <img src="assets\DSC_0936-Edit.JPG"   />
      <img src="assets\DSC_1059-Edit.JPG"   />
      <img src="assets\IMG_20190516_174719_815.jpg"   />
      <img src="assets\DSC_0990-Edit.JPG"   />
    </div>
  </section>

  <footer>
      <p>(c) @kazenomonon</p>
  </footer>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Namakemon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>